# Predictor-context, privileged-state, backend, and integrated 3P builds.

$(BP_CONTEXT_ALWAYS_BRANCH_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=1 -o $(BP_CONTEXT_ALWAYS_BRANCH_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_NOPREDECODE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-Ptb_bp_context.BP_TYPE=1 \
		-Ptb_bp_context.ENABLE_PREDECODE_TARGETS=0 \
		-o $(BP_CONTEXT_NOPREDECODE_SIM_BUILD) \
		$(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_ALWAYS_DECLINE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=2 -o $(BP_CONTEXT_ALWAYS_DECLINE_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_REPEAT_LAST_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=3 -o $(BP_CONTEXT_REPEAT_LAST_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_BTFNT_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=4 -o $(BP_CONTEXT_BTFNT_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_BIMODAL_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=5 -o $(BP_CONTEXT_BIMODAL_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_GSHARE_BTB_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=6 -o $(BP_CONTEXT_GSHARE_BTB_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_GSHARE_BTB_512_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=7 -o $(BP_CONTEXT_GSHARE_BTB_512_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_TOURNAMENT_BTB_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=8 -o $(BP_CONTEXT_TOURNAMENT_BTB_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(EXCEPT_SIM_BUILD): $(EXCEPT_SIM_SRCS) $(EXCEPT_SRCS) $(ISA_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(EXCEPT_SIM_BUILD) $(EXCEPT_SIM_SRCS)

$(EXEC_SYSTEM_CSR_SIM_BUILD): $(EXEC_SYSTEM_CSR_SIM_SRCS) $(EXEC_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(EXEC_SYSTEM_CSR_SIM_BUILD) $(EXEC_SYSTEM_CSR_SIM_SRCS)

$(TRAP_CONTEXT_SIM_BUILD): $(TRAP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(TRAP_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(TRAP_CONTEXT_SIM_SRCS)

$(PRIV_CONTEXT_SIM_BUILD): $(PRIV_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(PRIV_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(PRIV_CONTEXT_SIM_SRCS)

$(IRQ_CONTEXT_SIM_BUILD): $(IRQ_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(IRQ_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(IRQ_CONTEXT_SIM_SRCS)

$(LOAD_USE_CONTEXT_SIM_BUILD): $(LOAD_USE_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(LOAD_USE_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(LOAD_USE_CONTEXT_SIM_SRCS)

$(REG_OWNER_SIM_BUILD): $(REG_OWNER_SIM_SRCS) rtl/core/dispatch/reg_map.v $(ISA_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(REG_OWNER_SIM_BUILD) rtl/core/dispatch/reg_map.v $(REG_OWNER_SIM_SRCS)

$(RETIRE_QUEUE_3P_SIM_BUILD): rtl/core/retire/retire_queue_3p.v \
	rtl/core/retire/retire_records_3p.v tb/tb_retire_queue_3p.sv
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(RETIRE_QUEUE_3P_SIM_BUILD) \
		rtl/core/retire/retire_queue_3p.v \
		rtl/core/retire/retire_records_3p.v tb/tb_retire_queue_3p.sv

$(RETIRE_3P_SIM_BUILD): rtl/core/retire/retire_3p.v tb/tb_retire_3p.sv
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(RETIRE_3P_SIM_BUILD) \
		rtl/core/retire/retire_3p.v tb/tb_retire_3p.sv

$(BACKEND_3P_SIM_BUILD): tb/tb_backend_3p.sv $(BACKEND_SRCS) \
	$(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) $(RETIRE_SRCS) \
	$(EXCEPT_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_backend_3p -o $(BACKEND_3P_SIM_BUILD) \
		-Ptb_backend_3p.RELAX_HAZARDS=$(BACKEND_3P_RELAX_HAZARDS) \
		-Ptb_backend_3p.PHYS_REG_COUNT=$(BACKEND_3P_PHYS_REG_COUNT) \
		$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
		$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ARITH_DEPS) tb/tb_backend_3p.sv

$(TOP_3P_SIM_BUILD): tb/tb_top_3p.sv rtl/openrv64_top.sv $(CORE_SRCS) \
	$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(TOP_3P_SIM_BUILD) \
		rtl/openrv64_top.sv $(CORE_SRCS) tb/tb_top_3p.sv

$(CORE_3P_MAGIC_VERILATOR_BUILD): tb/tb_core_3p_magic.sv \
		$(CORE_3P_AXI_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_3P_MAGIC_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 0 -Irtl \
		--top-module tb_core_3p_magic \
		-GFETCH_ALT_LOOKASIDE=$(CORE_3P_MAGIC_MODE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(CORE_3P_MAGIC_CONFIDENCE_GATE) \
		-GBP_TYPE=$(CORE_3P_MAGIC_BP_TYPE) \
		-GCOMPLETION_FORWARD_MASK=$(CORE_3P_MAGIC_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(CORE_3P_MAGIC_BRANCH_FORWARD_MASK) \
		-GENABLE_FULL_FORWARDING=$(CORE_3P_MAGIC_FULL_FORWARDING) \
		-GRELAX_WAW=$(CORE_3P_MAGIC_RELAX_WAW) \
		-GRELAX_HAZARDS=$(CORE_3P_MAGIC_RELAX_HAZARDS) \
		-GRETIRE_DEPTH=$(CORE_3P_MAGIC_RETIRE_DEPTH) \
		-GPHYS_REG_COUNT=$(CORE_3P_MAGIC_PHYS_REG_COUNT) \
		-GISSUE_WINDOW=$(CORE_3P_MAGIC_ISSUE_WINDOW) \
		-GSPECULATION_WINDOW=$(CORE_3P_MAGIC_SPECULATION_WINDOW) \
		-GSRAM_BYTES=$(CORE_3P_MAGIC_SRAM_BYTES) \
		--Mdir $(CORE_3P_MAGIC_VERILATOR_DIR) \
		-o core_3p_magic_tb $(CORE_3P_AXI_SRCS) \
		tb/tb_core_3p_magic.sv

$(CORE_3P_CCX_L2_VERILATOR_BUILD): tb/tb_top_3p_soc.v \
		$(CORE_3P_AXI_SRCS) $(CORE_COMPLEX_SRCS) \
		$(AXI_DDR3_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_3P_CCX_L2_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 0 -Irtl \
		--top-module tb_top_3p_soc \
		-GFETCH_CAROUSEL=$(CORE_3P_CCX_L2_FETCH_CAROUSEL) \
		-GFETCH_ALT_LOOKASIDE=$(CORE_3P_CCX_L2_MODE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(CORE_3P_CCX_L2_CONFIDENCE_GATE) \
		-GFETCH_ALT_PAIR_STACK_DEPTH=$(CORE_3P_CCX_L2_PAIR_STACK_DEPTH) \
		-GBP_TYPE=$(CORE_3P_CCX_L2_BP_TYPE) \
		-GCOMPLETION_FORWARD_MASK=$(CORE_3P_CCX_L2_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(CORE_3P_CCX_L2_BRANCH_FORWARD_MASK) \
		-GENABLE_FULL_FORWARDING=$(CORE_3P_CCX_L2_FULL_FORWARDING) \
		-GRELAX_WAW=$(CORE_3P_CCX_L2_RELAX_WAW) \
		-GRELAX_HAZARDS=$(CORE_3P_CCX_L2_RELAX_HAZARDS) \
		-GISSUE_WINDOW=$(CORE_3P_CCX_L2_ISSUE_WINDOW) \
		-GSPECULATION_WINDOW=$(CORE_3P_CCX_L2_SPECULATION_WINDOW) \
		-GRETIRE_DEPTH=$(CORE_3P_CCX_L2_RETIRE_DEPTH) \
		-GPHYS_REG_COUNT=$(CORE_3P_CCX_L2_PHYS_REG_COUNT) \
		-GENABLE_POSTED_STORES=$(CORE_3P_CCX_L2_POSTED_STORES) \
		-GRAM_BYTES=$(CORE_3P_CCX_L2_RAM_BYTES) \
		-GSPEC_LOAD_BASE=64\'d$(CORE_3P_CCX_L2_SPEC_LOAD_BASE) \
		-GSPEC_LOAD_SIZE=64\'d$(CORE_3P_CCX_L2_SPEC_LOAD_SIZE) \
		-GL1I_CACHE_BYTES=$(CORE_3P_CCX_L2_L1I_BYTES) \
		-GL1D_CACHE_BYTES=$(CORE_3P_CCX_L2_L1D_BYTES) \
		-GL2_TLB_ENTRIES=$(CORE_3P_CCX_L2_TLB_ENTRIES) \
		-GL2_TLB_WAYS=$(CORE_3P_CCX_L2_TLB_WAYS) \
		-GL2_BYTES=$(CORE_3P_CCX_L2_L2_BYTES) \
		-GL2_WAYS=$(CORE_3P_CCX_L2_L2_WAYS) \
		-GL2_MERGE_ENTRIES=$(CORE_3P_CCX_L2_MSHR_ENTRIES) \
		-GGENBUS_READ_BUFFER_DEPTH=$(CORE_3P_CCX_L2_GENBUS_READ_DEPTH) \
		-GGENBUS_WRITE_BUFFER_DEPTH=$(CORE_3P_CCX_L2_GENBUS_WRITE_DEPTH) \
		-GL1D_PREFETCH_ENABLE=$(CORE_3P_CCX_L2_L1D_PREFETCH_ENABLE) \
		-GL1D_PREFETCH_STREAMS=$(CORE_3P_CCX_L2_L1D_PREFETCH_STREAMS) \
		-GL1D_PREFETCH_DISTANCE=$(CORE_3P_CCX_L2_L1D_PREFETCH_DISTANCE) \
		-GL1D_PREFETCH_ADAPTIVE_ENABLE=$(CORE_3P_CCX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE) \
		-GL1D_PREFETCH_MAX_DISTANCE=$(CORE_3P_CCX_L2_L1D_PREFETCH_MAX_DISTANCE) \
		-GL1D_PREFETCH_QUEUE_LINES=$(CORE_3P_CCX_L2_L1D_PREFETCH_QUEUE_LINES) \
		-GL1D_PREFETCH_OUTSTANDING=$(CORE_3P_CCX_L2_L1D_PREFETCH_OUTSTANDING) \
		-GL1D_PREFETCH_DEMAND_RESERVE=$(CORE_3P_CCX_L2_L1D_PREFETCH_DEMAND_RESERVE) \
		-GDDR3_ENABLE=$(CORE_3P_CCX_L2_DDR3) \
		-GDDR3_READ_QUEUE_DEPTH=$(CORE_3P_CCX_L2_DDR3_READ_QUEUE_DEPTH) \
		-GDDR3_WRITE_QUEUE_DEPTH=$(CORE_3P_CCX_L2_DDR3_WRITE_QUEUE_DEPTH) \
		-GDDR3_COMMAND_QUEUE_DEPTH=$(CORE_3P_CCX_L2_DDR3_COMMAND_QUEUE_DEPTH) \
		-GMEMORY_TIMING_MODEL=$(CORE_3P_CCX_L2_MEMORY_TIMING_MODEL) \
		--Mdir $(CORE_3P_CCX_L2_VERILATOR_DIR) \
		-o core_3p_ccx_l2_tb $(CORE_3P_AXI_SRCS) \
		$(CORE_COMPLEX_SRCS) $(AXI_DDR3_SRCS) tb/tb_top_3p_soc.v

$(CORE_4H_3P_VERILATOR_BUILD): tb/tb_4h_3p.sv \
		$(CORE_3P_AXI_SRCS) rtl/complex/protocol/line_crossbar.v \
		$(CCX_L2_SRCS) $(CCX_COHERENT_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_4H_3P_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 32 \
		--threads $(CORE_4H_3P_VERILATOR_THREADS) -Irtl \
		-GL1D_PREFETCH_ENABLE=$(CORE_4H_3P_L1D_PREFETCH_ENABLE) \
		-GSPEC_LOAD_BASE=64\'d$(CORE_4H_3P_SPEC_LOAD_BASE) \
		-GSPEC_LOAD_SIZE=64\'d$(CORE_4H_3P_SPEC_LOAD_SIZE) \
		--output-split 20000 --output-split-cfuncs 2000 \
		--top-module tb_4h_3p \
		--Mdir $(CORE_4H_3P_VERILATOR_DIR) \
		-o core_4h_3p_tb $(CORE_3P_AXI_SRCS) \
		rtl/complex/protocol/line_crossbar.v \
		$(CCX_L2_SRCS) $(CCX_COHERENT_SRCS) tb/tb_4h_3p.sv

$(TOP_AXI_3P_SIM_BUILD): tb/tb_top_axi_3p.sv rtl/openrv64_top_3p.v \
	$(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS) \
	$(SOC_BUS_SRCS) $(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) \
	$(UART_SRCS) $(GPIO_SRCS) $(TIMER_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_top_axi_3p \
		-Ptb_top_axi_3p.RAM_BYTES=16777216 \
		-Ptb_top_axi_3p.BP_TYPE=$(AXI_3P_BP_TYPE) \
		-Ptb_top_axi_3p.BP_RAS_ENABLE=$(AXI_3P_BP_RAS_ENABLE) \
		-Ptb_top_axi_3p.BP_RAS_DEPTH=$(AXI_3P_BP_RAS_DEPTH) \
		-Ptb_top_axi_3p.BP_BIMODAL_ENTRIES=$(AXI_3P_BP_BIMODAL_ENTRIES) \
		-Ptb_top_axi_3p.BP_BIMODAL_COUNTER_BITS=$(AXI_3P_BP_BIMODAL_COUNTER_BITS) \
		-Ptb_top_axi_3p.BP_BIMODAL_UPDATE_DEPTH=$(AXI_3P_BP_BIMODAL_UPDATE_DEPTH) \
		-Ptb_top_axi_3p.BP_GSHARE_ENTRIES=$(AXI_3P_BP_GSHARE_ENTRIES) \
		-Ptb_top_axi_3p.BP_GSHARE_COUNTER_BITS=$(AXI_3P_BP_GSHARE_COUNTER_BITS) \
		-Ptb_top_axi_3p.BP_BTB_ENTRIES=$(AXI_3P_BP_BTB_ENTRIES) \
		-Ptb_top_axi_3p.BP_BTB_TAG_BITS=$(AXI_3P_BP_BTB_TAG_BITS) \
		-Ptb_top_axi_3p.BP_INFLIGHT_DEPTH=$(AXI_3P_BP_INFLIGHT_DEPTH) \
		-Ptb_top_axi_3p.RETIRE_DEPTH=$(AXI_3P_RETIRE_DEPTH) \
		-Ptb_top_axi_3p.PHYS_REG_COUNT=$(AXI_3P_PHYS_REG_COUNT) \
		-Ptb_top_axi_3p.COMPLETION_FORWARD_MASK=$(AXI_3P_COMPLETION_FORWARD_MASK) \
		-Ptb_top_axi_3p.BRANCH_FORWARD_MASK=$(AXI_3P_BRANCH_FORWARD_MASK) \
		-Ptb_top_axi_3p.FULL_FORWARDING=$(AXI_3P_FULL_FORWARDING) \
		-Ptb_top_axi_3p.RELAX_WAW=$(AXI_3P_RELAX_WAW) \
		-Ptb_top_axi_3p.RELAX_HAZARDS=$(AXI_3P_RELAX_HAZARDS) \
		-Ptb_top_axi_3p.ISSUE_WINDOW=$(AXI_3P_ISSUE_WINDOW) \
		-Ptb_top_axi_3p.SPECULATION_WINDOW=$(AXI_3P_SPECULATION_WINDOW) \
		-Ptb_top_axi_3p.POSTED_STORES=$(AXI_3P_POSTED_STORES) \
		-Ptb_top_axi_3p.FREE_BRANCHES=$(AXI_3P_FREE_BRANCHES) \
		-Ptb_top_axi_3p.EQ_BRANCH_PAIRING=$(AXI_3P_EQ_BRANCH_PAIRING) \
		-Ptb_top_axi_3p.ORACLE_BRANCHES=$(AXI_3P_ORACLE_BRANCHES) \
		-Ptb_top_axi_3p.FREE_L1_REFILLS=$(AXI_3P_FREE_L1_REFILLS) \
		-Ptb_top_axi_3p.FREE_L1I_REFILLS=$(AXI_3P_FREE_L1I_REFILLS) \
		-Ptb_top_axi_3p.FREE_L1D_REFILLS=$(AXI_3P_FREE_L1D_REFILLS) \
		-Ptb_top_axi_3p.FREELOADER=$(AXI_3P_FREELOADER) \
		-Ptb_top_axi_3p.FREELOADER_LATENCY=$(AXI_3P_FREELOADER_LATENCY) \
		-Ptb_top_axi_3p.L1D_PREFETCH_ENABLE=$(AXI_3P_L1D_PREFETCH_ENABLE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_MAX_STRIDE_LINES=$(AXI_3P_L1D_PREFETCH_MAX_STRIDE_LINES) \
		-Ptb_top_axi_3p.L1D_PREFETCH_STREAMS=$(AXI_3P_L1D_PREFETCH_STREAMS) \
		-Ptb_top_axi_3p.L1D_PREFETCH_DISTANCE=$(AXI_3P_L1D_PREFETCH_DISTANCE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_ADAPTIVE_ENABLE=$(AXI_3P_L1D_PREFETCH_ADAPTIVE_ENABLE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_MAX_DISTANCE=$(AXI_3P_L1D_PREFETCH_MAX_DISTANCE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_QUEUE_LINES=$(AXI_3P_L1D_PREFETCH_QUEUE_LINES) \
		-Ptb_top_axi_3p.L1D_PREFETCH_OUTSTANDING=$(AXI_3P_L1D_PREFETCH_OUTSTANDING) \
		-Ptb_top_axi_3p.L1D_PREFETCH_DEMAND_RESERVE=$(AXI_3P_L1D_PREFETCH_DEMAND_RESERVE) \
		-Ptb_top_axi_3p.FETCH_ALT_LOOKASIDE=$(AXI_3P_FETCH_ALT_LOOKASIDE) \
		-Ptb_top_axi_3p.FETCH_ALT_CONFIDENCE_GATE=$(AXI_3P_FETCH_ALT_CONFIDENCE_GATE) \
		-o $(TOP_AXI_3P_SIM_BUILD) rtl/openrv64_top_3p.v $(CORE_SRCS) \
		$(SOC_BUS_SRCS) $(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) \
		$(UART_SRCS) $(GPIO_SRCS) $(TIMER_SRCS) \
		tb/tb_top_axi_3p.sv
